// Code generated by "stringer -type=NalUnitType -trimprefix=NalUnitType"; DO NOT EDIT.

package h264

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NalUnitTypeCodedSliceNonIdr-1]
	_ = x[NalUnitTypeCodedSliceDataPartitionA-2]
	_ = x[NalUnitTypeCodedSliceDataPartitionB-3]
	_ = x[NalUnitTypeCodedSliceDataPartitionC-4]
	_ = x[NalUnitTypeCodedSliceIdr-5]
	_ = x[NalUnitTypeSEI-6]
	_ = x[NalUnitTypeSPS-7]
	_ = x[NalUnitTypePPS-8]
	_ = x[NalUnitTypeAUD-9]
	_ = x[NalUnitTypeEndOfSequence-10]
	_ = x[NalUnitTypeEndOfStream-11]
	_ = x[NalUnitTypeFiller-12]
	_ = x[NalUnitTypeSpsExt-13]
	_ = x[NalUnitTypePrefixNalUnit-14]
	_ = x[NalUnitTypeSubsetSeqParameterSet-15]
	_ = x[NalUnitTypeDepthParameterSet-16]
	_ = x[NalUnitTypeCodedSliceAux-19]
	_ = x[NalUnitTypeCodedSliceExtension-20]
	_ = x[NalUnitTypeCodedSliceExtension3D-21]
}

const (
	_NalUnitType_name_0 = "CodedSliceNonIdrCodedSliceDataPartitionACodedSliceDataPartitionBCodedSliceDataPartitionCCodedSliceIdrSEISPSPPSAUDEndOfSequenceEndOfStreamFillerSpsExtPrefixNalUnitSubsetSeqParameterSetDepthParameterSet"
	_NalUnitType_name_1 = "CodedSliceAuxCodedSliceExtensionCodedSliceExtension3D"
)

var (
	_NalUnitType_index_0 = [...]uint8{0, 16, 40, 64, 88, 101, 104, 107, 110, 113, 126, 137, 143, 149, 162, 183, 200}
	_NalUnitType_index_1 = [...]uint8{0, 13, 32, 53}
)

func (i NalUnitType) String() string {
	switch {
	case 1 <= i && i <= 16:
		i -= 1
		return _NalUnitType_name_0[_NalUnitType_index_0[i]:_NalUnitType_index_0[i+1]]
	case 19 <= i && i <= 21:
		i -= 19
		return _NalUnitType_name_1[_NalUnitType_index_1[i]:_NalUnitType_index_1[i+1]]
	default:
		return "NalUnitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
