// Code generated by "stringer -type=SeiType -trimprefix=SeiType"; DO NOT EDIT.

package h264

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeiTypeBufferingPeriod-0]
	_ = x[SeiTypePicTiming-1]
	_ = x[SeiTypePanScanRect-2]
	_ = x[SeiTypeFillerPayload-3]
	_ = x[SeiTypeUserDataRegisteredItuTT35-4]
	_ = x[SeiTypeUserDataUnregistered-5]
	_ = x[SeiTypeRecoveryPoint-6]
	_ = x[SeiTypeDecRefPicMarkingRepetition-7]
	_ = x[SeiTypeSparePic-8]
	_ = x[SeiTypeSceneInfo-9]
	_ = x[SeiTypeSubSeqInfo-10]
	_ = x[SeiTypeSubSeqLayerCharacteristics-11]
	_ = x[SeiTypeSubSeqCharacteristics-12]
	_ = x[SeiTypeFullFrameFreeze-13]
	_ = x[SeiTypeFullFrameFreezeRelease-14]
	_ = x[SeiTypeFullFrameSnapshot-15]
	_ = x[SeiTypeProgressiveRefinementSegmentStart-16]
	_ = x[SeiTypeProgressiveRefinementSegmentEnd-17]
	_ = x[SeiTypeMotionConstrainedSliceGroupSet-18]
	_ = x[SeiTypeFilmGrainCharacteristics-19]
	_ = x[SeiTypeDeblockingFilterDisplayPreference-20]
	_ = x[SeiTypeStereoVideoInfo-21]
	_ = x[SeiTypePostFilterHint-22]
	_ = x[SeiTypeToneMappingInfo-23]
	_ = x[SeiTypeScalabilityInfo-24]
	_ = x[SeiTypeSubPicScalableLayer-25]
	_ = x[SeiTypeNonRequiredLayerRep-26]
	_ = x[SeiTypePriorityLayerInfo-27]
	_ = x[SeiTypeLayersNotPresent-28]
	_ = x[SeiTypeLayerDependencyChange-29]
	_ = x[SeiTypeScalableNesting-30]
	_ = x[SeiTypeBaseLayerTemporalHrd-31]
	_ = x[SeiTypeQualityLayerIntegrityCheck-32]
	_ = x[SeiTypeRedundantPicProperty-33]
	_ = x[SeiTypeTl0DepRepIndex-34]
	_ = x[SeiTypeTlSwitchingPoint-35]
	_ = x[SeiTypeParallelDecodingInfo-36]
	_ = x[SeiTypeMvcScalableNesting-37]
	_ = x[SeiTypeViewScalabilityInfo-38]
	_ = x[SeiTypeMultiviewSceneInfo-39]
	_ = x[SeiTypeMultiviewAcquisitionInfo-40]
	_ = x[SeiTypeNonRequiredViewComponent-41]
	_ = x[SeiTypeViewDependencyChange-42]
	_ = x[SeiTypeOperationPointsNotPresent-43]
	_ = x[SeiTypeBaseViewTemporalHrd-44]
	_ = x[SeiTypeFramePackingArrangement-45]
	_ = x[SeiTypeMultiviewViewPosition-46]
	_ = x[SeiTypeDisplayOrientation-47]
	_ = x[SeiTypeMvcdScalableNesting-48]
	_ = x[SeiTypeMvcdViewScalabilityInfo-49]
	_ = x[SeiTypeDepthRepresentationInfo-50]
	_ = x[SeiTypeThreeDimensionalReferenceDisplaysInfo-51]
	_ = x[SeiTypeDepthTiming-52]
	_ = x[SeiTypeDepthSamplingInfo-53]
	_ = x[SeiTypeConstrainedDepthParameterSetIdentifier-54]
	_ = x[SeiTypeGreenMetadata-56]
	_ = x[SeiTypeMasteringDisplayColourVolume-137]
	_ = x[SeiTypeColourRemappingInfo-142]
	_ = x[SeiTypeContentLightLevelInfo-144]
	_ = x[SeiTypeAlternativeTransferCharacteristics-147]
	_ = x[SeiTypeAmbientViewingEnvironment-148]
	_ = x[SeiTypeContentColourVolume-149]
	_ = x[SeiTypeEquirectangularProjection-150]
	_ = x[SeiTypeCubemapProjection-151]
	_ = x[SeiTypeSphereRotation-154]
	_ = x[SeiTypeRegionwisePacking-155]
	_ = x[SeiTypeOmniViewport-156]
	_ = x[SeiTypeAlternativeDepthInfo-181]
	_ = x[SeiTypeSeiManifest-200]
	_ = x[SeiTypeSeiPrefixIndication-201]
	_ = x[SeiTypeAnnotatedRegions-202]
	_ = x[SeiTypeShutterIntervalInfo-205]
}

const (
	_SeiType_name_0 = "BufferingPeriodPicTimingPanScanRectFillerPayloadUserDataRegisteredItuTT35UserDataUnregisteredRecoveryPointDecRefPicMarkingRepetitionSparePicSceneInfoSubSeqInfoSubSeqLayerCharacteristicsSubSeqCharacteristicsFullFrameFreezeFullFrameFreezeReleaseFullFrameSnapshotProgressiveRefinementSegmentStartProgressiveRefinementSegmentEndMotionConstrainedSliceGroupSetFilmGrainCharacteristicsDeblockingFilterDisplayPreferenceStereoVideoInfoPostFilterHintToneMappingInfoScalabilityInfoSubPicScalableLayerNonRequiredLayerRepPriorityLayerInfoLayersNotPresentLayerDependencyChangeScalableNestingBaseLayerTemporalHrdQualityLayerIntegrityCheckRedundantPicPropertyTl0DepRepIndexTlSwitchingPointParallelDecodingInfoMvcScalableNestingViewScalabilityInfoMultiviewSceneInfoMultiviewAcquisitionInfoNonRequiredViewComponentViewDependencyChangeOperationPointsNotPresentBaseViewTemporalHrdFramePackingArrangementMultiviewViewPositionDisplayOrientationMvcdScalableNestingMvcdViewScalabilityInfoDepthRepresentationInfoThreeDimensionalReferenceDisplaysInfoDepthTimingDepthSamplingInfoConstrainedDepthParameterSetIdentifier"
	_SeiType_name_1 = "GreenMetadata"
	_SeiType_name_2 = "MasteringDisplayColourVolume"
	_SeiType_name_3 = "ColourRemappingInfo"
	_SeiType_name_4 = "ContentLightLevelInfo"
	_SeiType_name_5 = "AlternativeTransferCharacteristicsAmbientViewingEnvironmentContentColourVolumeEquirectangularProjectionCubemapProjection"
	_SeiType_name_6 = "SphereRotationRegionwisePackingOmniViewport"
	_SeiType_name_7 = "AlternativeDepthInfo"
	_SeiType_name_8 = "SeiManifestSeiPrefixIndicationAnnotatedRegions"
	_SeiType_name_9 = "ShutterIntervalInfo"
)

var (
	_SeiType_index_0 = [...]uint16{0, 15, 24, 35, 48, 73, 93, 106, 132, 140, 149, 159, 185, 206, 221, 243, 260, 293, 324, 354, 378, 411, 426, 440, 455, 470, 489, 508, 525, 541, 562, 577, 597, 623, 643, 657, 673, 693, 711, 730, 748, 772, 796, 816, 841, 860, 883, 904, 922, 941, 964, 987, 1024, 1035, 1052, 1090}
	_SeiType_index_5 = [...]uint8{0, 34, 59, 78, 103, 120}
	_SeiType_index_6 = [...]uint8{0, 14, 31, 43}
	_SeiType_index_8 = [...]uint8{0, 11, 30, 46}
)

func (i SeiType) String() string {
	switch {
	case 0 <= i && i <= 54:
		return _SeiType_name_0[_SeiType_index_0[i]:_SeiType_index_0[i+1]]
	case i == 56:
		return _SeiType_name_1
	case i == 137:
		return _SeiType_name_2
	case i == 142:
		return _SeiType_name_3
	case i == 144:
		return _SeiType_name_4
	case 147 <= i && i <= 151:
		i -= 147
		return _SeiType_name_5[_SeiType_index_5[i]:_SeiType_index_5[i+1]]
	case 154 <= i && i <= 156:
		i -= 154
		return _SeiType_name_6[_SeiType_index_6[i]:_SeiType_index_6[i+1]]
	case i == 181:
		return _SeiType_name_7
	case 200 <= i && i <= 202:
		i -= 200
		return _SeiType_name_8[_SeiType_index_8[i]:_SeiType_index_8[i+1]]
	case i == 205:
		return _SeiType_name_9
	default:
		return "SeiType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
